In [2]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)

input_x = np.array([[1,0,0,0],[1,0,1,1],[0,1,0,1]])
print(input_x)


[[1 0 0 0]
 [1 0 1 1]
 [0 1 0 1]]


In [3]:
input_xT = input_x.T
print(input_xT)

[[1 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]]


In [5]:
output_y = np.array([[1],[1],[0]])
output_yT = output_y.T
print(output_yT)

[[1 1 0]]


In [5]:
inputlayer = input_xT.shape[0] #jumlah neuron di input
print(inputlayer)

4


In [6]:
hiddenlayer = 3 #jumlah neuron lanjutan setelah neuron input
outputlayer = 1 #jumlah output layer
w_in = np.random.uniform(size=(inputlayer,hiddenlayer)) #weight xinput
w_out = np.random.uniform(size=(hiddenlayer,outputlayer)) #weight dari hidden layer input (sigmoid dari neuron pertama)
print(w_in)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]


In [9]:
print(w_out)

[[0.51423444]
 [0.59241457]
 [0.04645041]]


In [7]:
w_in.shape,w_out.shape

((4, 3), (3, 1))

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

dot_mat_input_win = np.dot(w_in.T,input_xT)
hidden_layer = sigmoid(dot_mat_input_win)
print(hidden_layer)

[[0.59255557 0.75780746 0.78696563]
 [0.72125881 0.8626498  0.54403639]
 [0.67524268 0.90912675 0.75508227]]
